//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Server
{
	using Server.Database;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GameServer
	{
		private List<ClientUser> Users
		{
			get;
			set;
		}

		private bool fetchUsers()
		{
			throw new System.NotImplementedException();
		}

	}
}

