//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Server
{
    using Model;
    using Database;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Client;

    public interface IAuthServer 
	{
		string IP { get;set; }

		string Port { get;set; }

		DBManager DBConnector { get;set; }

		int loginUser(ClientUser User);

		bool sendAuthKey(ClientUser User, GameServer Server);

		int registerUser(ClientUser User);

		bool recoverPassword(string Username);

	}
}

