//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Server
{
    using Client;
    using Model;
    using Database;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public interface IGameServer 
	{
		List<Game> ActiveGames { get;set; }

		Dictionary <ClientUser, string> LoggedUsers { get;set; }

		Dictionary<ClientUser, Game> PlayingUsers { get;set; }

		DBManager DBConnector { get;set; }

		bool registerUser(ClientUser User, string AuthID);

		bool assignGameRoom(ClientUser User);

		List<Game> findEmptyGames();

		bool fetchAuthKey(ClientUser User, string AuthKey);

		List<Card> fetchGameCards(ClientUser User);

	}
}

