//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Server.Database
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Database
	{
		private string IP
		{
			get;
			set;
		}

		private string Password
		{
			get;
			set;
		}

		private string Username
		{
			get;
			set;
		}

	}
}

