//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Server.Database
{
    using Client;
    using Model;
    using Server;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public interface DBManager
	{
		string DBName { get;set; }

		int checkUserLogin(ClientUser User);

		int registerUser(ClientUser User);

		List<ClientUser> loadUsers();

	}
}

