//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Client
{
	using Model;
	using Server;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface Client  : IAuthServer, IGameServer
	{
		string Username { get;set; }

		string Password { get;set; }

		string Email { get;set; }

		IAuthServer AuthServer { get;set; }

		IGameServer GameServer { get;set; }

		int register();

		int connectToGameServer();

		int login();

	}
}

