//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Card
	{
        enum Type {
            Black = 0,
            White = 1
        }

        internal int CardType {
            get;
            set;
        }

        internal int CardID
		{
			get;
			set;
		}

        internal string CardText
		{
			get;
			set;
		}

        public Card(int cardID, string cardText, int cardType) {
            this.CardID = cardID;
            this.CardText = cardText;
            this.CardType = cardType;
        }
	}
}