//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using Server;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Game : IGameServer
	{
		private object RoomID
		{
			get;
			set;
		}

		private List <User> Users
		{
			get;
			set;
		}

		private User Judge
		{
			get;
			set;
		}

		private object Cards : Dictionary <User, List<Card>>
		{
			get;
			set;
		}

		public virtual Room Room
		{
			get;
			set;
		}

		public virtual Card Card
		{
			get;
			set;
		}

		public virtual IEnumerable<User> User
		{
			get;
			set;
		}

		public virtual bool registerUser(ClientUser User, string AuthID)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool assignGameRoom(ClientUser User)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<Game> findEmptyGames()
		{
			throw new System.NotImplementedException();
		}

		public virtual bool fetchAuthKey(ClientUser User, string AuthKey)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<Card> fetchGameCards(ClientUser User)
		{
			throw new System.NotImplementedException();
		}

	}
}

