//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Premium User : User
	{
		private List <Achievement> Achievement
		{
			get;
			set;
		}

		public virtual List<Achievement> getAchievements()
		{
			throw new System.NotImplementedException();
		}

	}
}

