//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PremiumUser : User
    {
        private List<Achievement> Achieves
        {
            get;
            set;
        }

        public PremiumUser(int UserID, string Username, string Password) : base(UserID, Username, Password)
        {
            Achieves = new List<Achievement>();
        }


		public virtual List<Achievement> getAchievements()
		{
			throw new System.NotImplementedException();
		}

	}
}

