//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class User
	{
		private int UserID
		{
			get;
			set;
		}

		private string AuthID
		{
			get;
			set;
		}

		private string Password
		{
			get;
			set;
		}

		private string Username
		{
			get;
			set;
		}

		public User(string UserID, string Username, string Password)
		{
		}

	}
}

